version: '3'

services:
  poc-ansible-host:
    image: poc-ansible-host
    privileged: true
    build:
      context: ..
      dockerfile: ./host/Dockerfile
      args:
        - USERNAME=${USER}
        - USERID=${UID:-1000}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    # networks:
    #     - host
    ports:
      - "9999:29999"
      - "2222:2222"

# networks:
#   host:
#     external:
#       name: host
