version: '3.4'

services:
  poc-ansible-service:
    build:
      context: ".."
      dockerfile: ./services/Dockerfile
      args:
        - MY_TOKEN=${MY_TOKEN}
    hostname: poc-ansible-service
    command: bash /opt/app/conda-activate.sh python -m http.server 29999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "29999:29999"
