version: '3.4'

services:
  poc-ansible-service:
    build:
      context: ".."
      dockerfile: ./services/Dockerfile
      args:
        - MY_TOKEN=${MY_TOKEN}
    hostname: poc-ansible-service
    env_file:
      - .env
    ports:
      - "7777:8000"
