---
- hosts: all
  connection: ssh

  tasks:
    - name: Update and upgrade apt packages
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # One day

    - name: Install prerequisites for Docker repository
      become: yes
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
        update_cache: yes

    - name: Add Docker GPG key
      become: yes
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      become: yes
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

    - name: Install Docker CE
      become: yes
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        update_cache: yes

    - name: Install prerequisites for docker-compose
      become: yes
      apt:
        name: ['python3-pip', 'python3-setuptools', 'virtualenv']

    - name: Install docker-compose
      become: yes
      pip:
        name: docker-compose

    - name: Add docker group
      become: yes
      shell: "usermod -aG docker $(whoami) && newgrp docker"
