- hosts: all
  connection: ssh

  tasks:
    - name: Add docker group
      become: yes
      shell: echo $(whoami) && usermod -aG docker $(whoami)

    # - name: Update user group
    #   become: yes
    #   shell: id -g && newgrp docker
