---
- hosts: all
  connection: ssh

  tasks:
    - name: Create and start services
      docker_compose:
        project_src: /opt/app/services
        build: yes
        remove_orphans: yes
        debug: yes
      async: 900
      poll: 05
      register: output

    - name: Debug output of docker-compose
      debug:
        var: output
