---
- hosts: all
  connection: ssh

  tasks:
    - name: Create and start services
      docker_compose:
        project_name: services-group
        definition:
            service:
              build: "../services/Dockerfile"
              command: "python -m http.server 29999"
              ports:
                - "29999:29999"
      async: 900
      poll: 05
      register: output

    - name: Debug output of docker-compose
      debug:
        var: output
